version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: receptionistdb
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  dbmate:
    image: amacneil/dbmate
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/receptionistdb?sslmode=disable
    volumes:
      - ./db/migrations:/db/migrations
    command: up

  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - dbmate
    env_file:
      - .env

  ui:
    build: ./ui
    ports:
      - "8501:8501"
    depends_on:
      - api
