version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: receptionistdb
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  dbmate:
    image: amacneil/dbmate
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/receptionistdb?sslmode=disable
    volumes:
      - ./db/migrations:/db/migrations
    command: up

  local_agent:
    build: ./local_agent
    container_name: local_agent
    restart: on-failure
    env_file:
      - .env
    working_dir: /app
    stdin_open: true
    tty: true
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/receptionistdb?sslmode=disable
    depends_on:
      - db
    command: >
      sh -c "
        uv venv &&
        uv sync &&
        uv run python main.py
      "
